name: coldguard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_litert_lm: ^0.3.0
  mqtt_client: ^10.11.11
  path_provider: ^2.1.5
  permission_handler: ^12.0.3
  file_picker: ^8.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
